insert into lusers values (100,'sam');
insert into creds values (100,'pass','sam',100);
insert into projects values (100,'This website was made completely by me! It features a front-end designed by me in Angular, and a back-end REST API created in Spring Boot','This Website','http://github.com/halfcreative/mysite','GitHub',100);
insert into tech values (100,'Angular');
insert into tech values (200,'Java');
insert into tech values (300,'Spring');
insert into project_tech values (100,100);
insert into project_tech values (100,200);
insert into project_tech values (100,300);
insert into history values (100,'Revature','Software developer for Revature. 10 Weeks of training in Full-Stack web application development. Contracted to Cognizant for work on a project with Toyota Motors North America.',null,'Software Developer','July 2018',100);